gdal_translate -of AAIGrid D:\a\data\marspec\MARSPEC_10m\Core_Variables_10m\bathy_10m D:\a\data\marspec\MARSPEC_10m\ascii\bathy_10m.asc
gdal_translate -of AAIGrid D:\a\data\marspec\MARSPEC_10m\Core_Variables_10m\biogeo01_10m D:\a\data\marspec\MARSPEC_10m\ascii\biogeo01_10m.asc
gdal_translate -of AAIGrid D:\a\data\marspec\MARSPEC_10m\Core_Variables_10m\biogeo02_10m D:\a\data\marspec\MARSPEC_10m\ascii\biogeo02_10m.asc
gdal_translate -of AAIGrid D:\a\data\marspec\MARSPEC_10m\Core_Variables_10m\biogeo03_10m D:\a\data\marspec\MARSPEC_10m\ascii\biogeo03_10m.asc
gdal_translate -of AAIGrid D:\a\data\marspec\MARSPEC_10m\Core_Variables_10m\biogeo04_10m D:\a\data\marspec\MARSPEC_10m\ascii\biogeo04_10m.asc
gdal_translate -of AAIGrid D:\a\data\marspec\MARSPEC_10m\Core_Variables_10m\biogeo05_10m D:\a\data\marspec\MARSPEC_10m\ascii\biogeo05_10m.asc
gdal_translate -of AAIGrid D:\a\data\marspec\MARSPEC_10m\Core_Variables_10m\biogeo06_10m D:\a\data\marspec\MARSPEC_10m\ascii\biogeo06_10m.asc
gdal_translate -of AAIGrid D:\a\data\marspec\MARSPEC_10m\Core_Variables_10m\biogeo07_10m D:\a\data\marspec\MARSPEC_10m\ascii\biogeo07_10m.asc
gdal_translate -of AAIGrid D:\a\data\marspec\MARSPEC_10m\Core_Variables_10m\biogeo08_10m D:\a\data\marspec\MARSPEC_10m\ascii\biogeo08_10m.asc
gdal_translate -of AAIGrid D:\a\data\marspec\MARSPEC_10m\Core_Variables_10m\biogeo09_10m D:\a\data\marspec\MARSPEC_10m\ascii\biogeo09_10m.asc
gdal_translate -of AAIGrid D:\a\data\marspec\MARSPEC_10m\Core_Variables_10m\biogeo10_10m D:\a\data\marspec\MARSPEC_10m\ascii\biogeo10_10m.asc
gdal_translate -of AAIGrid D:\a\data\marspec\MARSPEC_10m\Core_Variables_10m\biogeo11_10m D:\a\data\marspec\MARSPEC_10m\ascii\biogeo11_10m.asc
gdal_translate -of AAIGrid D:\a\data\marspec\MARSPEC_10m\Core_Variables_10m\biogeo12_10m D:\a\data\marspec\MARSPEC_10m\ascii\biogeo12_10m.asc
gdal_translate -of AAIGrid D:\a\data\marspec\MARSPEC_10m\Core_Variables_10m\biogeo13_10m D:\a\data\marspec\MARSPEC_10m\ascii\biogeo13_10m.asc
gdal_translate -of AAIGrid D:\a\data\marspec\MARSPEC_10m\Core_Variables_10m\biogeo14_10m D:\a\data\marspec\MARSPEC_10m\ascii\biogeo14_10m.asc
gdal_translate -of AAIGrid D:\a\data\marspec\MARSPEC_10m\Core_Variables_10m\biogeo15_10m D:\a\data\marspec\MARSPEC_10m\ascii\biogeo15_10m.asc
gdal_translate -of AAIGrid D:\a\data\marspec\MARSPEC_10m\Core_Variables_10m\biogeo16_10m D:\a\data\marspec\MARSPEC_10m\ascii\biogeo16_10m.asc
gdal_translate -of AAIGrid D:\a\data\marspec\MARSPEC_10m\Core_Variables_10m\biogeo17_10m D:\a\data\marspec\MARSPEC_10m\ascii\biogeo17_10m.asc
gdal_translate -of AAIGrid D:\a\data\marspec\MARSPEC_10m\Monthly_Variables_10m\Salinity\sss01_10m D:\a\data\marspec\MARSPEC_10m\ascii\sss01_10m.asc
gdal_translate -of AAIGrid D:\a\data\marspec\MARSPEC_10m\Monthly_Variables_10m\Salinity\sss02_10m D:\a\data\marspec\MARSPEC_10m\ascii\sss02_10m.asc
gdal_translate -of AAIGrid D:\a\data\marspec\MARSPEC_10m\Monthly_Variables_10m\Salinity\sss03_10m D:\a\data\marspec\MARSPEC_10m\ascii\sss03_10m.asc
gdal_translate -of AAIGrid D:\a\data\marspec\MARSPEC_10m\Monthly_Variables_10m\Salinity\sss04_10m D:\a\data\marspec\MARSPEC_10m\ascii\sss04_10m.asc
gdal_translate -of AAIGrid D:\a\data\marspec\MARSPEC_10m\Monthly_Variables_10m\Salinity\sss05_10m D:\a\data\marspec\MARSPEC_10m\ascii\sss05_10m.asc
gdal_translate -of AAIGrid D:\a\data\marspec\MARSPEC_10m\Monthly_Variables_10m\Salinity\sss06_10m D:\a\data\marspec\MARSPEC_10m\ascii\sss06_10m.asc
gdal_translate -of AAIGrid D:\a\data\marspec\MARSPEC_10m\Monthly_Variables_10m\Salinity\sss07_10m D:\a\data\marspec\MARSPEC_10m\ascii\sss07_10m.asc
gdal_translate -of AAIGrid D:\a\data\marspec\MARSPEC_10m\Monthly_Variables_10m\Salinity\sss08_10m D:\a\data\marspec\MARSPEC_10m\ascii\sss08_10m.asc
gdal_translate -of AAIGrid D:\a\data\marspec\MARSPEC_10m\Monthly_Variables_10m\Salinity\sss09_10m D:\a\data\marspec\MARSPEC_10m\ascii\sss09_10m.asc
gdal_translate -of AAIGrid D:\a\data\marspec\MARSPEC_10m\Monthly_Variables_10m\Salinity\sss10_10m D:\a\data\marspec\MARSPEC_10m\ascii\sss10_10m.asc
gdal_translate -of AAIGrid D:\a\data\marspec\MARSPEC_10m\Monthly_Variables_10m\Salinity\sss11_10m D:\a\data\marspec\MARSPEC_10m\ascii\sss11_10m.asc
gdal_translate -of AAIGrid D:\a\data\marspec\MARSPEC_10m\Monthly_Variables_10m\Salinity\sss12_10m D:\a\data\marspec\MARSPEC_10m\ascii\sss12_10m.asc
gdal_translate -of AAIGrid D:\a\data\marspec\MARSPEC_10m\Monthly_Variables_10m\Temperature\sst01_10m D:\a\data\marspec\MARSPEC_10m\ascii\sst01_10m.asc
gdal_translate -of AAIGrid D:\a\data\marspec\MARSPEC_10m\Monthly_Variables_10m\Temperature\sst02_10m D:\a\data\marspec\MARSPEC_10m\ascii\sst02_10m.asc
gdal_translate -of AAIGrid D:\a\data\marspec\MARSPEC_10m\Monthly_Variables_10m\Temperature\sst03_10m D:\a\data\marspec\MARSPEC_10m\ascii\sst03_10m.asc
gdal_translate -of AAIGrid D:\a\data\marspec\MARSPEC_10m\Monthly_Variables_10m\Temperature\sst04_10m D:\a\data\marspec\MARSPEC_10m\ascii\sst04_10m.asc
gdal_translate -of AAIGrid D:\a\data\marspec\MARSPEC_10m\Monthly_Variables_10m\Temperature\sst05_10m D:\a\data\marspec\MARSPEC_10m\ascii\sst05_10m.asc
gdal_translate -of AAIGrid D:\a\data\marspec\MARSPEC_10m\Monthly_Variables_10m\Temperature\sst06_10m D:\a\data\marspec\MARSPEC_10m\ascii\sst06_10m.asc
gdal_translate -of AAIGrid D:\a\data\marspec\MARSPEC_10m\Monthly_Variables_10m\Temperature\sst07_10m D:\a\data\marspec\MARSPEC_10m\ascii\sst07_10m.asc
gdal_translate -of AAIGrid D:\a\data\marspec\MARSPEC_10m\Monthly_Variables_10m\Temperature\sst08_10m D:\a\data\marspec\MARSPEC_10m\ascii\sst08_10m.asc
gdal_translate -of AAIGrid D:\a\data\marspec\MARSPEC_10m\Monthly_Variables_10m\Temperature\sst09_10m D:\a\data\marspec\MARSPEC_10m\ascii\sst09_10m.asc
gdal_translate -of AAIGrid D:\a\data\marspec\MARSPEC_10m\Monthly_Variables_10m\Temperature\sst10_10m D:\a\data\marspec\MARSPEC_10m\ascii\sst10_10m.asc
gdal_translate -of AAIGrid D:\a\data\marspec\MARSPEC_10m\Monthly_Variables_10m\Temperature\sst11_10m D:\a\data\marspec\MARSPEC_10m\ascii\sst11_10m.asc
gdal_translate -of AAIGrid D:\a\data\marspec\MARSPEC_10m\Monthly_Variables_10m\Temperature\sst12_10m D:\a\data\marspec\MARSPEC_10m\ascii\sst12_10m.asc
