gdalwarp -of GTiff -multi -t_srs "+proj=cea +lon_0=0 +lat_ts=30 +x_0=0 +y_0=0 +datum=WGS84 +ellps=WGS84 +units=m +no_defs" "D:\a\data\BioOracle_scenarios_30s_min250\A1B\2100\salinity.asc" "D:\a\data\BioOracle_scenarios_30s_min250_equal_area\salinity.tiff"
gdal_translate -of AAIGrid "D:\a\data\BioOracle_scenarios_30s_min250_equal_area\salinity.tiff" "D:\a\data\BioOracle_scenarios_30s_min250_equal_area\A1B\2100\salinity.asc"
del "D:\a\data\BioOracle_scenarios_30s_min250_equal_area\salinity.tiff"
gdalwarp -of GTiff -multi -t_srs "+proj=cea +lon_0=0 +lat_ts=30 +x_0=0 +y_0=0 +datum=WGS84 +ellps=WGS84 +units=m +no_defs" "D:\a\data\BioOracle_scenarios_30s_min250\A1B\2100\sst_max.asc" "D:\a\data\BioOracle_scenarios_30s_min250_equal_area\sst_max.tiff"
gdal_translate -of AAIGrid "D:\a\data\BioOracle_scenarios_30s_min250_equal_area\sst_max.tiff" "D:\a\data\BioOracle_scenarios_30s_min250_equal_area\A1B\2100\sst_max.asc"
del "D:\a\data\BioOracle_scenarios_30s_min250_equal_area\sst_max.tiff"
gdalwarp -of GTiff -multi -t_srs "+proj=cea +lon_0=0 +lat_ts=30 +x_0=0 +y_0=0 +datum=WGS84 +ellps=WGS84 +units=m +no_defs" "D:\a\data\BioOracle_scenarios_30s_min250\A1B\2100\sst_mean.asc" "D:\a\data\BioOracle_scenarios_30s_min250_equal_area\sst_mean.tiff"
gdal_translate -of AAIGrid "D:\a\data\BioOracle_scenarios_30s_min250_equal_area\sst_mean.tiff" "D:\a\data\BioOracle_scenarios_30s_min250_equal_area\A1B\2100\sst_mean.asc"
del "D:\a\data\BioOracle_scenarios_30s_min250_equal_area\sst_mean.tiff"
gdalwarp -of GTiff -multi -t_srs "+proj=cea +lon_0=0 +lat_ts=30 +x_0=0 +y_0=0 +datum=WGS84 +ellps=WGS84 +units=m +no_defs" "D:\a\data\BioOracle_scenarios_30s_min250\A1B\2100\sst_min.asc" "D:\a\data\BioOracle_scenarios_30s_min250_equal_area\sst_min.tiff"
gdal_translate -of AAIGrid "D:\a\data\BioOracle_scenarios_30s_min250_equal_area\sst_min.tiff" "D:\a\data\BioOracle_scenarios_30s_min250_equal_area\A1B\2100\sst_min.asc"
del "D:\a\data\BioOracle_scenarios_30s_min250_equal_area\sst_min.tiff"
gdalwarp -of GTiff -multi -t_srs "+proj=cea +lon_0=0 +lat_ts=30 +x_0=0 +y_0=0 +datum=WGS84 +ellps=WGS84 +units=m +no_defs" "D:\a\data\BioOracle_scenarios_30s_min250\A1B\2100\sst_range.asc" "D:\a\data\BioOracle_scenarios_30s_min250_equal_area\sst_range.tiff"
gdal_translate -of AAIGrid "D:\a\data\BioOracle_scenarios_30s_min250_equal_area\sst_range.tiff" "D:\a\data\BioOracle_scenarios_30s_min250_equal_area\A1B\2100\sst_range.asc"
del "D:\a\data\BioOracle_scenarios_30s_min250_equal_area\sst_range.tiff"
gdalwarp -of GTiff -multi -t_srs "+proj=cea +lon_0=0 +lat_ts=30 +x_0=0 +y_0=0 +datum=WGS84 +ellps=WGS84 +units=m +no_defs" "D:\a\data\BioOracle_scenarios_30s_min250\A1B\2200\salinity.asc" "D:\a\data\BioOracle_scenarios_30s_min250_equal_area\salinity.tiff"
gdal_translate -of AAIGrid "D:\a\data\BioOracle_scenarios_30s_min250_equal_area\salinity.tiff" "D:\a\data\BioOracle_scenarios_30s_min250_equal_area\A1B\2200\salinity.asc"
del "D:\a\data\BioOracle_scenarios_30s_min250_equal_area\salinity.tiff"
gdalwarp -of GTiff -multi -t_srs "+proj=cea +lon_0=0 +lat_ts=30 +x_0=0 +y_0=0 +datum=WGS84 +ellps=WGS84 +units=m +no_defs" "D:\a\data\BioOracle_scenarios_30s_min250\A1B\2200\sst_max.asc" "D:\a\data\BioOracle_scenarios_30s_min250_equal_area\sst_max.tiff"
gdal_translate -of AAIGrid "D:\a\data\BioOracle_scenarios_30s_min250_equal_area\sst_max.tiff" "D:\a\data\BioOracle_scenarios_30s_min250_equal_area\A1B\2200\sst_max.asc"
del "D:\a\data\BioOracle_scenarios_30s_min250_equal_area\sst_max.tiff"
gdalwarp -of GTiff -multi -t_srs "+proj=cea +lon_0=0 +lat_ts=30 +x_0=0 +y_0=0 +datum=WGS84 +ellps=WGS84 +units=m +no_defs" "D:\a\data\BioOracle_scenarios_30s_min250\A1B\2200\sst_mean.asc" "D:\a\data\BioOracle_scenarios_30s_min250_equal_area\sst_mean.tiff"
gdal_translate -of AAIGrid "D:\a\data\BioOracle_scenarios_30s_min250_equal_area\sst_mean.tiff" "D:\a\data\BioOracle_scenarios_30s_min250_equal_area\A1B\2200\sst_mean.asc"
del "D:\a\data\BioOracle_scenarios_30s_min250_equal_area\sst_mean.tiff"
gdalwarp -of GTiff -multi -t_srs "+proj=cea +lon_0=0 +lat_ts=30 +x_0=0 +y_0=0 +datum=WGS84 +ellps=WGS84 +units=m +no_defs" "D:\a\data\BioOracle_scenarios_30s_min250\A1B\2200\sst_min.asc" "D:\a\data\BioOracle_scenarios_30s_min250_equal_area\sst_min.tiff"
gdal_translate -of AAIGrid "D:\a\data\BioOracle_scenarios_30s_min250_equal_area\sst_min.tiff" "D:\a\data\BioOracle_scenarios_30s_min250_equal_area\A1B\2200\sst_min.asc"
del "D:\a\data\BioOracle_scenarios_30s_min250_equal_area\sst_min.tiff"
gdalwarp -of GTiff -multi -t_srs "+proj=cea +lon_0=0 +lat_ts=30 +x_0=0 +y_0=0 +datum=WGS84 +ellps=WGS84 +units=m +no_defs" "D:\a\data\BioOracle_scenarios_30s_min250\A1B\2200\sst_range.asc" "D:\a\data\BioOracle_scenarios_30s_min250_equal_area\sst_range.tiff"
gdal_translate -of AAIGrid "D:\a\data\BioOracle_scenarios_30s_min250_equal_area\sst_range.tiff" "D:\a\data\BioOracle_scenarios_30s_min250_equal_area\A1B\2200\sst_range.asc"
del "D:\a\data\BioOracle_scenarios_30s_min250_equal_area\sst_range.tiff"
gdalwarp -of GTiff -multi -t_srs "+proj=cea +lon_0=0 +lat_ts=30 +x_0=0 +y_0=0 +datum=WGS84 +ellps=WGS84 +units=m +no_defs" "D:\a\data\BioOracle_scenarios_30s_min250\A2\2100\salinity.asc" "D:\a\data\BioOracle_scenarios_30s_min250_equal_area\salinity.tiff"
gdal_translate -of AAIGrid "D:\a\data\BioOracle_scenarios_30s_min250_equal_area\salinity.tiff" "D:\a\data\BioOracle_scenarios_30s_min250_equal_area\A2\2100\salinity.asc"
del "D:\a\data\BioOracle_scenarios_30s_min250_equal_area\salinity.tiff"
gdalwarp -of GTiff -multi -t_srs "+proj=cea +lon_0=0 +lat_ts=30 +x_0=0 +y_0=0 +datum=WGS84 +ellps=WGS84 +units=m +no_defs" "D:\a\data\BioOracle_scenarios_30s_min250\A2\2100\sst_max.asc" "D:\a\data\BioOracle_scenarios_30s_min250_equal_area\sst_max.tiff"
gdal_translate -of AAIGrid "D:\a\data\BioOracle_scenarios_30s_min250_equal_area\sst_max.tiff" "D:\a\data\BioOracle_scenarios_30s_min250_equal_area\A2\2100\sst_max.asc"
del "D:\a\data\BioOracle_scenarios_30s_min250_equal_area\sst_max.tiff"
gdalwarp -of GTiff -multi -t_srs "+proj=cea +lon_0=0 +lat_ts=30 +x_0=0 +y_0=0 +datum=WGS84 +ellps=WGS84 +units=m +no_defs" "D:\a\data\BioOracle_scenarios_30s_min250\A2\2100\sst_mean.asc" "D:\a\data\BioOracle_scenarios_30s_min250_equal_area\sst_mean.tiff"
gdal_translate -of AAIGrid "D:\a\data\BioOracle_scenarios_30s_min250_equal_area\sst_mean.tiff" "D:\a\data\BioOracle_scenarios_30s_min250_equal_area\A2\2100\sst_mean.asc"
del "D:\a\data\BioOracle_scenarios_30s_min250_equal_area\sst_mean.tiff"
gdalwarp -of GTiff -multi -t_srs "+proj=cea +lon_0=0 +lat_ts=30 +x_0=0 +y_0=0 +datum=WGS84 +ellps=WGS84 +units=m +no_defs" "D:\a\data\BioOracle_scenarios_30s_min250\A2\2100\sst_min.asc" "D:\a\data\BioOracle_scenarios_30s_min250_equal_area\sst_min.tiff"
gdal_translate -of AAIGrid "D:\a\data\BioOracle_scenarios_30s_min250_equal_area\sst_min.tiff" "D:\a\data\BioOracle_scenarios_30s_min250_equal_area\A2\2100\sst_min.asc"
del "D:\a\data\BioOracle_scenarios_30s_min250_equal_area\sst_min.tiff"
gdalwarp -of GTiff -multi -t_srs "+proj=cea +lon_0=0 +lat_ts=30 +x_0=0 +y_0=0 +datum=WGS84 +ellps=WGS84 +units=m +no_defs" "D:\a\data\BioOracle_scenarios_30s_min250\A2\2100\sst_range.asc" "D:\a\data\BioOracle_scenarios_30s_min250_equal_area\sst_range.tiff"
gdal_translate -of AAIGrid "D:\a\data\BioOracle_scenarios_30s_min250_equal_area\sst_range.tiff" "D:\a\data\BioOracle_scenarios_30s_min250_equal_area\A2\2100\sst_range.asc"
del "D:\a\data\BioOracle_scenarios_30s_min250_equal_area\sst_range.tiff"
gdalwarp -of GTiff -multi -t_srs "+proj=cea +lon_0=0 +lat_ts=30 +x_0=0 +y_0=0 +datum=WGS84 +ellps=WGS84 +units=m +no_defs" "D:\a\data\BioOracle_scenarios_30s_min250\B1\2100\salinity.asc" "D:\a\data\BioOracle_scenarios_30s_min250_equal_area\salinity.tiff"
gdal_translate -of AAIGrid "D:\a\data\BioOracle_scenarios_30s_min250_equal_area\salinity.tiff" "D:\a\data\BioOracle_scenarios_30s_min250_equal_area\B1\2100\salinity.asc"
del "D:\a\data\BioOracle_scenarios_30s_min250_equal_area\salinity.tiff"
gdalwarp -of GTiff -multi -t_srs "+proj=cea +lon_0=0 +lat_ts=30 +x_0=0 +y_0=0 +datum=WGS84 +ellps=WGS84 +units=m +no_defs" "D:\a\data\BioOracle_scenarios_30s_min250\B1\2100\sst_max.asc" "D:\a\data\BioOracle_scenarios_30s_min250_equal_area\sst_max.tiff"
gdal_translate -of AAIGrid "D:\a\data\BioOracle_scenarios_30s_min250_equal_area\sst_max.tiff" "D:\a\data\BioOracle_scenarios_30s_min250_equal_area\B1\2100\sst_max.asc"
del "D:\a\data\BioOracle_scenarios_30s_min250_equal_area\sst_max.tiff"
gdalwarp -of GTiff -multi -t_srs "+proj=cea +lon_0=0 +lat_ts=30 +x_0=0 +y_0=0 +datum=WGS84 +ellps=WGS84 +units=m +no_defs" "D:\a\data\BioOracle_scenarios_30s_min250\B1\2100\sst_mean.asc" "D:\a\data\BioOracle_scenarios_30s_min250_equal_area\sst_mean.tiff"
gdal_translate -of AAIGrid "D:\a\data\BioOracle_scenarios_30s_min250_equal_area\sst_mean.tiff" "D:\a\data\BioOracle_scenarios_30s_min250_equal_area\B1\2100\sst_mean.asc"
del "D:\a\data\BioOracle_scenarios_30s_min250_equal_area\sst_mean.tiff"
gdalwarp -of GTiff -multi -t_srs "+proj=cea +lon_0=0 +lat_ts=30 +x_0=0 +y_0=0 +datum=WGS84 +ellps=WGS84 +units=m +no_defs" "D:\a\data\BioOracle_scenarios_30s_min250\B1\2100\sst_min.asc" "D:\a\data\BioOracle_scenarios_30s_min250_equal_area\sst_min.tiff"
gdal_translate -of AAIGrid "D:\a\data\BioOracle_scenarios_30s_min250_equal_area\sst_min.tiff" "D:\a\data\BioOracle_scenarios_30s_min250_equal_area\B1\2100\sst_min.asc"
del "D:\a\data\BioOracle_scenarios_30s_min250_equal_area\sst_min.tiff"
gdalwarp -of GTiff -multi -t_srs "+proj=cea +lon_0=0 +lat_ts=30 +x_0=0 +y_0=0 +datum=WGS84 +ellps=WGS84 +units=m +no_defs" "D:\a\data\BioOracle_scenarios_30s_min250\B1\2100\sst_range.asc" "D:\a\data\BioOracle_scenarios_30s_min250_equal_area\sst_range.tiff"
gdal_translate -of AAIGrid "D:\a\data\BioOracle_scenarios_30s_min250_equal_area\sst_range.tiff" "D:\a\data\BioOracle_scenarios_30s_min250_equal_area\B1\2100\sst_range.asc"
del "D:\a\data\BioOracle_scenarios_30s_min250_equal_area\sst_range.tiff"
gdalwarp -of GTiff -multi -t_srs "+proj=cea +lon_0=0 +lat_ts=30 +x_0=0 +y_0=0 +datum=WGS84 +ellps=WGS84 +units=m +no_defs" "D:\a\data\BioOracle_scenarios_30s_min250\B1\2200\salinity.asc" "D:\a\data\BioOracle_scenarios_30s_min250_equal_area\salinity.tiff"
gdal_translate -of AAIGrid "D:\a\data\BioOracle_scenarios_30s_min250_equal_area\salinity.tiff" "D:\a\data\BioOracle_scenarios_30s_min250_equal_area\B1\2200\salinity.asc"
del "D:\a\data\BioOracle_scenarios_30s_min250_equal_area\salinity.tiff"
gdalwarp -of GTiff -multi -t_srs "+proj=cea +lon_0=0 +lat_ts=30 +x_0=0 +y_0=0 +datum=WGS84 +ellps=WGS84 +units=m +no_defs" "D:\a\data\BioOracle_scenarios_30s_min250\B1\2200\sst_max.asc" "D:\a\data\BioOracle_scenarios_30s_min250_equal_area\sst_max.tiff"
gdal_translate -of AAIGrid "D:\a\data\BioOracle_scenarios_30s_min250_equal_area\sst_max.tiff" "D:\a\data\BioOracle_scenarios_30s_min250_equal_area\B1\2200\sst_max.asc"
del "D:\a\data\BioOracle_scenarios_30s_min250_equal_area\sst_max.tiff"
gdalwarp -of GTiff -multi -t_srs "+proj=cea +lon_0=0 +lat_ts=30 +x_0=0 +y_0=0 +datum=WGS84 +ellps=WGS84 +units=m +no_defs" "D:\a\data\BioOracle_scenarios_30s_min250\B1\2200\sst_mean.asc" "D:\a\data\BioOracle_scenarios_30s_min250_equal_area\sst_mean.tiff"
gdal_translate -of AAIGrid "D:\a\data\BioOracle_scenarios_30s_min250_equal_area\sst_mean.tiff" "D:\a\data\BioOracle_scenarios_30s_min250_equal_area\B1\2200\sst_mean.asc"
del "D:\a\data\BioOracle_scenarios_30s_min250_equal_area\sst_mean.tiff"
gdalwarp -of GTiff -multi -t_srs "+proj=cea +lon_0=0 +lat_ts=30 +x_0=0 +y_0=0 +datum=WGS84 +ellps=WGS84 +units=m +no_defs" "D:\a\data\BioOracle_scenarios_30s_min250\B1\2200\sst_min.asc" "D:\a\data\BioOracle_scenarios_30s_min250_equal_area\sst_min.tiff"
gdal_translate -of AAIGrid "D:\a\data\BioOracle_scenarios_30s_min250_equal_area\sst_min.tiff" "D:\a\data\BioOracle_scenarios_30s_min250_equal_area\B1\2200\sst_min.asc"
del "D:\a\data\BioOracle_scenarios_30s_min250_equal_area\sst_min.tiff"
gdalwarp -of GTiff -multi -t_srs "+proj=cea +lon_0=0 +lat_ts=30 +x_0=0 +y_0=0 +datum=WGS84 +ellps=WGS84 +units=m +no_defs" "D:\a\data\BioOracle_scenarios_30s_min250\B1\2200\sst_range.asc" "D:\a\data\BioOracle_scenarios_30s_min250_equal_area\sst_range.tiff"
gdal_translate -of AAIGrid "D:\a\data\BioOracle_scenarios_30s_min250_equal_area\sst_range.tiff" "D:\a\data\BioOracle_scenarios_30s_min250_equal_area\B1\2200\sst_range.asc"
del "D:\a\data\BioOracle_scenarios_30s_min250_equal_area\sst_range.tiff"
