gdalwarp -of GTiff -multi -t_srs "+proj=cea +lon_0=0 +lat_ts=30 +x_0=0 +y_0=0 +datum=WGS84 +ellps=WGS84 +units=m +no_defs" "D:\a\data\marspec\MARSPEC_10m\ascii\bathy_10m.asc" "D:\a\data\marspec\MARSPEC_10m\ascii_equalarea\bathy_10m.tiff"
gdal_translate -of AAIGrid "D:\a\data\marspec\MARSPEC_10m\ascii_equalarea\bathy_10m.tiff" "D:\a\data\marspec\MARSPEC_10m\ascii_equalarea\bathy_10m.asc"
del "D:\a\data\marspec\MARSPEC_10m\ascii_equalarea\bathy_10m.tiff"
gdalwarp -of GTiff -multi -t_srs "+proj=cea +lon_0=0 +lat_ts=30 +x_0=0 +y_0=0 +datum=WGS84 +ellps=WGS84 +units=m +no_defs" "D:\a\data\marspec\MARSPEC_10m\ascii\biogeo01_aspect_EW_10m.asc" "D:\a\data\marspec\MARSPEC_10m\ascii_equalarea\biogeo01_aspect_EW_10m.tiff"
gdal_translate -of AAIGrid "D:\a\data\marspec\MARSPEC_10m\ascii_equalarea\biogeo01_aspect_EW_10m.tiff" "D:\a\data\marspec\MARSPEC_10m\ascii_equalarea\biogeo01_aspect_EW_10m.asc"
del "D:\a\data\marspec\MARSPEC_10m\ascii_equalarea\biogeo01_aspect_EW_10m.tiff"
gdalwarp -of GTiff -multi -t_srs "+proj=cea +lon_0=0 +lat_ts=30 +x_0=0 +y_0=0 +datum=WGS84 +ellps=WGS84 +units=m +no_defs" "D:\a\data\marspec\MARSPEC_10m\ascii\biogeo02_aspect_NS_10m.asc" "D:\a\data\marspec\MARSPEC_10m\ascii_equalarea\biogeo02_aspect_NS_10m.tiff"
gdal_translate -of AAIGrid "D:\a\data\marspec\MARSPEC_10m\ascii_equalarea\biogeo02_aspect_NS_10m.tiff" "D:\a\data\marspec\MARSPEC_10m\ascii_equalarea\biogeo02_aspect_NS_10m.asc"
del "D:\a\data\marspec\MARSPEC_10m\ascii_equalarea\biogeo02_aspect_NS_10m.tiff"
gdalwarp -of GTiff -multi -t_srs "+proj=cea +lon_0=0 +lat_ts=30 +x_0=0 +y_0=0 +datum=WGS84 +ellps=WGS84 +units=m +no_defs" "D:\a\data\marspec\MARSPEC_10m\ascii\biogeo03_plan_curvature_10m.asc" "D:\a\data\marspec\MARSPEC_10m\ascii_equalarea\biogeo03_plan_curvature_10m.tiff"
gdal_translate -of AAIGrid "D:\a\data\marspec\MARSPEC_10m\ascii_equalarea\biogeo03_plan_curvature_10m.tiff" "D:\a\data\marspec\MARSPEC_10m\ascii_equalarea\biogeo03_plan_curvature_10m.asc"
del "D:\a\data\marspec\MARSPEC_10m\ascii_equalarea\biogeo03_plan_curvature_10m.tiff"
gdalwarp -of GTiff -multi -t_srs "+proj=cea +lon_0=0 +lat_ts=30 +x_0=0 +y_0=0 +datum=WGS84 +ellps=WGS84 +units=m +no_defs" "D:\a\data\marspec\MARSPEC_10m\ascii\biogeo04_profile_curvature_10m.asc" "D:\a\data\marspec\MARSPEC_10m\ascii_equalarea\biogeo04_profile_curvature_10m.tiff"
gdal_translate -of AAIGrid "D:\a\data\marspec\MARSPEC_10m\ascii_equalarea\biogeo04_profile_curvature_10m.tiff" "D:\a\data\marspec\MARSPEC_10m\ascii_equalarea\biogeo04_profile_curvature_10m.asc"
del "D:\a\data\marspec\MARSPEC_10m\ascii_equalarea\biogeo04_profile_curvature_10m.tiff"
gdalwarp -of GTiff -multi -t_srs "+proj=cea +lon_0=0 +lat_ts=30 +x_0=0 +y_0=0 +datum=WGS84 +ellps=WGS84 +units=m +no_defs" "D:\a\data\marspec\MARSPEC_10m\ascii\biogeo05_dist_shore_10m.asc" "D:\a\data\marspec\MARSPEC_10m\ascii_equalarea\biogeo05_dist_shore_10m.tiff"
gdal_translate -of AAIGrid "D:\a\data\marspec\MARSPEC_10m\ascii_equalarea\biogeo05_dist_shore_10m.tiff" "D:\a\data\marspec\MARSPEC_10m\ascii_equalarea\biogeo05_dist_shore_10m.asc"
del "D:\a\data\marspec\MARSPEC_10m\ascii_equalarea\biogeo05_dist_shore_10m.tiff"
gdalwarp -of GTiff -multi -t_srs "+proj=cea +lon_0=0 +lat_ts=30 +x_0=0 +y_0=0 +datum=WGS84 +ellps=WGS84 +units=m +no_defs" "D:\a\data\marspec\MARSPEC_10m\ascii\biogeo06_bathy_slope_10m.asc" "D:\a\data\marspec\MARSPEC_10m\ascii_equalarea\biogeo06_bathy_slope_10m.tiff"
gdal_translate -of AAIGrid "D:\a\data\marspec\MARSPEC_10m\ascii_equalarea\biogeo06_bathy_slope_10m.tiff" "D:\a\data\marspec\MARSPEC_10m\ascii_equalarea\biogeo06_bathy_slope_10m.asc"
del "D:\a\data\marspec\MARSPEC_10m\ascii_equalarea\biogeo06_bathy_slope_10m.tiff"
gdalwarp -of GTiff -multi -t_srs "+proj=cea +lon_0=0 +lat_ts=30 +x_0=0 +y_0=0 +datum=WGS84 +ellps=WGS84 +units=m +no_defs" "D:\a\data\marspec\MARSPEC_10m\ascii\biogeo07_concavity_10m.asc" "D:\a\data\marspec\MARSPEC_10m\ascii_equalarea\biogeo07_concavity_10m.tiff"
gdal_translate -of AAIGrid "D:\a\data\marspec\MARSPEC_10m\ascii_equalarea\biogeo07_concavity_10m.tiff" "D:\a\data\marspec\MARSPEC_10m\ascii_equalarea\biogeo07_concavity_10m.asc"
del "D:\a\data\marspec\MARSPEC_10m\ascii_equalarea\biogeo07_concavity_10m.tiff"
gdalwarp -of GTiff -multi -t_srs "+proj=cea +lon_0=0 +lat_ts=30 +x_0=0 +y_0=0 +datum=WGS84 +ellps=WGS84 +units=m +no_defs" "D:\a\data\marspec\MARSPEC_10m\ascii\biogeo08_sss_mean_10m.asc" "D:\a\data\marspec\MARSPEC_10m\ascii_equalarea\biogeo08_sss_mean_10m.tiff"
gdal_translate -of AAIGrid "D:\a\data\marspec\MARSPEC_10m\ascii_equalarea\biogeo08_sss_mean_10m.tiff" "D:\a\data\marspec\MARSPEC_10m\ascii_equalarea\biogeo08_sss_mean_10m.asc"
del "D:\a\data\marspec\MARSPEC_10m\ascii_equalarea\biogeo08_sss_mean_10m.tiff"
gdalwarp -of GTiff -multi -t_srs "+proj=cea +lon_0=0 +lat_ts=30 +x_0=0 +y_0=0 +datum=WGS84 +ellps=WGS84 +units=m +no_defs" "D:\a\data\marspec\MARSPEC_10m\ascii\biogeo09_sss_min_10m.asc" "D:\a\data\marspec\MARSPEC_10m\ascii_equalarea\biogeo09_sss_min_10m.tiff"
gdal_translate -of AAIGrid "D:\a\data\marspec\MARSPEC_10m\ascii_equalarea\biogeo09_sss_min_10m.tiff" "D:\a\data\marspec\MARSPEC_10m\ascii_equalarea\biogeo09_sss_min_10m.asc"
del "D:\a\data\marspec\MARSPEC_10m\ascii_equalarea\biogeo09_sss_min_10m.tiff"
gdalwarp -of GTiff -multi -t_srs "+proj=cea +lon_0=0 +lat_ts=30 +x_0=0 +y_0=0 +datum=WGS84 +ellps=WGS84 +units=m +no_defs" "D:\a\data\marspec\MARSPEC_10m\ascii\biogeo10_sss_max_10m.asc" "D:\a\data\marspec\MARSPEC_10m\ascii_equalarea\biogeo10_sss_max_10m.tiff"
gdal_translate -of AAIGrid "D:\a\data\marspec\MARSPEC_10m\ascii_equalarea\biogeo10_sss_max_10m.tiff" "D:\a\data\marspec\MARSPEC_10m\ascii_equalarea\biogeo10_sss_max_10m.asc"
del "D:\a\data\marspec\MARSPEC_10m\ascii_equalarea\biogeo10_sss_max_10m.tiff"
gdalwarp -of GTiff -multi -t_srs "+proj=cea +lon_0=0 +lat_ts=30 +x_0=0 +y_0=0 +datum=WGS84 +ellps=WGS84 +units=m +no_defs" "D:\a\data\marspec\MARSPEC_10m\ascii\biogeo11_sss_range_10m.asc" "D:\a\data\marspec\MARSPEC_10m\ascii_equalarea\biogeo11_sss_range_10m.tiff"
gdal_translate -of AAIGrid "D:\a\data\marspec\MARSPEC_10m\ascii_equalarea\biogeo11_sss_range_10m.tiff" "D:\a\data\marspec\MARSPEC_10m\ascii_equalarea\biogeo11_sss_range_10m.asc"
del "D:\a\data\marspec\MARSPEC_10m\ascii_equalarea\biogeo11_sss_range_10m.tiff"
gdalwarp -of GTiff -multi -t_srs "+proj=cea +lon_0=0 +lat_ts=30 +x_0=0 +y_0=0 +datum=WGS84 +ellps=WGS84 +units=m +no_defs" "D:\a\data\marspec\MARSPEC_10m\ascii\biogeo12_sss_variance_10m.asc" "D:\a\data\marspec\MARSPEC_10m\ascii_equalarea\biogeo12_sss_variance_10m.tiff"
gdal_translate -of AAIGrid "D:\a\data\marspec\MARSPEC_10m\ascii_equalarea\biogeo12_sss_variance_10m.tiff" "D:\a\data\marspec\MARSPEC_10m\ascii_equalarea\biogeo12_sss_variance_10m.asc"
del "D:\a\data\marspec\MARSPEC_10m\ascii_equalarea\biogeo12_sss_variance_10m.tiff"
gdalwarp -of GTiff -multi -t_srs "+proj=cea +lon_0=0 +lat_ts=30 +x_0=0 +y_0=0 +datum=WGS84 +ellps=WGS84 +units=m +no_defs" "D:\a\data\marspec\MARSPEC_10m\ascii\biogeo13_sst_mean_10m.asc" "D:\a\data\marspec\MARSPEC_10m\ascii_equalarea\biogeo13_sst_mean_10m.tiff"
gdal_translate -of AAIGrid "D:\a\data\marspec\MARSPEC_10m\ascii_equalarea\biogeo13_sst_mean_10m.tiff" "D:\a\data\marspec\MARSPEC_10m\ascii_equalarea\biogeo13_sst_mean_10m.asc"
del "D:\a\data\marspec\MARSPEC_10m\ascii_equalarea\biogeo13_sst_mean_10m.tiff"
gdalwarp -of GTiff -multi -t_srs "+proj=cea +lon_0=0 +lat_ts=30 +x_0=0 +y_0=0 +datum=WGS84 +ellps=WGS84 +units=m +no_defs" "D:\a\data\marspec\MARSPEC_10m\ascii\biogeo14_sst_min_10m.asc" "D:\a\data\marspec\MARSPEC_10m\ascii_equalarea\biogeo14_sst_min_10m.tiff"
gdal_translate -of AAIGrid "D:\a\data\marspec\MARSPEC_10m\ascii_equalarea\biogeo14_sst_min_10m.tiff" "D:\a\data\marspec\MARSPEC_10m\ascii_equalarea\biogeo14_sst_min_10m.asc"
del "D:\a\data\marspec\MARSPEC_10m\ascii_equalarea\biogeo14_sst_min_10m.tiff"
gdalwarp -of GTiff -multi -t_srs "+proj=cea +lon_0=0 +lat_ts=30 +x_0=0 +y_0=0 +datum=WGS84 +ellps=WGS84 +units=m +no_defs" "D:\a\data\marspec\MARSPEC_10m\ascii\biogeo15_sst_max_10m.asc" "D:\a\data\marspec\MARSPEC_10m\ascii_equalarea\biogeo15_sst_max_10m.tiff"
gdal_translate -of AAIGrid "D:\a\data\marspec\MARSPEC_10m\ascii_equalarea\biogeo15_sst_max_10m.tiff" "D:\a\data\marspec\MARSPEC_10m\ascii_equalarea\biogeo15_sst_max_10m.asc"
del "D:\a\data\marspec\MARSPEC_10m\ascii_equalarea\biogeo15_sst_max_10m.tiff"
gdalwarp -of GTiff -multi -t_srs "+proj=cea +lon_0=0 +lat_ts=30 +x_0=0 +y_0=0 +datum=WGS84 +ellps=WGS84 +units=m +no_defs" "D:\a\data\marspec\MARSPEC_10m\ascii\biogeo16_sst_range_10m.asc" "D:\a\data\marspec\MARSPEC_10m\ascii_equalarea\biogeo16_sst_range_10m.tiff"
gdal_translate -of AAIGrid "D:\a\data\marspec\MARSPEC_10m\ascii_equalarea\biogeo16_sst_range_10m.tiff" "D:\a\data\marspec\MARSPEC_10m\ascii_equalarea\biogeo16_sst_range_10m.asc"
del "D:\a\data\marspec\MARSPEC_10m\ascii_equalarea\biogeo16_sst_range_10m.tiff"
gdalwarp -of GTiff -multi -t_srs "+proj=cea +lon_0=0 +lat_ts=30 +x_0=0 +y_0=0 +datum=WGS84 +ellps=WGS84 +units=m +no_defs" "D:\a\data\marspec\MARSPEC_10m\ascii\biogeo17_sst_variance_10m.asc" "D:\a\data\marspec\MARSPEC_10m\ascii_equalarea\biogeo17_sst_variance_10m.tiff"
gdal_translate -of AAIGrid "D:\a\data\marspec\MARSPEC_10m\ascii_equalarea\biogeo17_sst_variance_10m.tiff" "D:\a\data\marspec\MARSPEC_10m\ascii_equalarea\biogeo17_sst_variance_10m.asc"
del "D:\a\data\marspec\MARSPEC_10m\ascii_equalarea\biogeo17_sst_variance_10m.tiff"
gdalwarp -of GTiff -multi -t_srs "+proj=cea +lon_0=0 +lat_ts=30 +x_0=0 +y_0=0 +datum=WGS84 +ellps=WGS84 +units=m +no_defs" "D:\a\data\marspec\MARSPEC_10m\ascii\sss01_10m.asc" "D:\a\data\marspec\MARSPEC_10m\ascii_equalarea\sss01_10m.tiff"
gdal_translate -of AAIGrid "D:\a\data\marspec\MARSPEC_10m\ascii_equalarea\sss01_10m.tiff" "D:\a\data\marspec\MARSPEC_10m\ascii_equalarea\sss01_10m.asc"
del "D:\a\data\marspec\MARSPEC_10m\ascii_equalarea\sss01_10m.tiff"
gdalwarp -of GTiff -multi -t_srs "+proj=cea +lon_0=0 +lat_ts=30 +x_0=0 +y_0=0 +datum=WGS84 +ellps=WGS84 +units=m +no_defs" "D:\a\data\marspec\MARSPEC_10m\ascii\sss02_10m.asc" "D:\a\data\marspec\MARSPEC_10m\ascii_equalarea\sss02_10m.tiff"
gdal_translate -of AAIGrid "D:\a\data\marspec\MARSPEC_10m\ascii_equalarea\sss02_10m.tiff" "D:\a\data\marspec\MARSPEC_10m\ascii_equalarea\sss02_10m.asc"
del "D:\a\data\marspec\MARSPEC_10m\ascii_equalarea\sss02_10m.tiff"
gdalwarp -of GTiff -multi -t_srs "+proj=cea +lon_0=0 +lat_ts=30 +x_0=0 +y_0=0 +datum=WGS84 +ellps=WGS84 +units=m +no_defs" "D:\a\data\marspec\MARSPEC_10m\ascii\sss03_10m.asc" "D:\a\data\marspec\MARSPEC_10m\ascii_equalarea\sss03_10m.tiff"
gdal_translate -of AAIGrid "D:\a\data\marspec\MARSPEC_10m\ascii_equalarea\sss03_10m.tiff" "D:\a\data\marspec\MARSPEC_10m\ascii_equalarea\sss03_10m.asc"
del "D:\a\data\marspec\MARSPEC_10m\ascii_equalarea\sss03_10m.tiff"
gdalwarp -of GTiff -multi -t_srs "+proj=cea +lon_0=0 +lat_ts=30 +x_0=0 +y_0=0 +datum=WGS84 +ellps=WGS84 +units=m +no_defs" "D:\a\data\marspec\MARSPEC_10m\ascii\sss04_10m.asc" "D:\a\data\marspec\MARSPEC_10m\ascii_equalarea\sss04_10m.tiff"
gdal_translate -of AAIGrid "D:\a\data\marspec\MARSPEC_10m\ascii_equalarea\sss04_10m.tiff" "D:\a\data\marspec\MARSPEC_10m\ascii_equalarea\sss04_10m.asc"
del "D:\a\data\marspec\MARSPEC_10m\ascii_equalarea\sss04_10m.tiff"
gdalwarp -of GTiff -multi -t_srs "+proj=cea +lon_0=0 +lat_ts=30 +x_0=0 +y_0=0 +datum=WGS84 +ellps=WGS84 +units=m +no_defs" "D:\a\data\marspec\MARSPEC_10m\ascii\sss05_10m.asc" "D:\a\data\marspec\MARSPEC_10m\ascii_equalarea\sss05_10m.tiff"
gdal_translate -of AAIGrid "D:\a\data\marspec\MARSPEC_10m\ascii_equalarea\sss05_10m.tiff" "D:\a\data\marspec\MARSPEC_10m\ascii_equalarea\sss05_10m.asc"
del "D:\a\data\marspec\MARSPEC_10m\ascii_equalarea\sss05_10m.tiff"
gdalwarp -of GTiff -multi -t_srs "+proj=cea +lon_0=0 +lat_ts=30 +x_0=0 +y_0=0 +datum=WGS84 +ellps=WGS84 +units=m +no_defs" "D:\a\data\marspec\MARSPEC_10m\ascii\sss06_10m.asc" "D:\a\data\marspec\MARSPEC_10m\ascii_equalarea\sss06_10m.tiff"
gdal_translate -of AAIGrid "D:\a\data\marspec\MARSPEC_10m\ascii_equalarea\sss06_10m.tiff" "D:\a\data\marspec\MARSPEC_10m\ascii_equalarea\sss06_10m.asc"
del "D:\a\data\marspec\MARSPEC_10m\ascii_equalarea\sss06_10m.tiff"
gdalwarp -of GTiff -multi -t_srs "+proj=cea +lon_0=0 +lat_ts=30 +x_0=0 +y_0=0 +datum=WGS84 +ellps=WGS84 +units=m +no_defs" "D:\a\data\marspec\MARSPEC_10m\ascii\sss07_10m.asc" "D:\a\data\marspec\MARSPEC_10m\ascii_equalarea\sss07_10m.tiff"
gdal_translate -of AAIGrid "D:\a\data\marspec\MARSPEC_10m\ascii_equalarea\sss07_10m.tiff" "D:\a\data\marspec\MARSPEC_10m\ascii_equalarea\sss07_10m.asc"
del "D:\a\data\marspec\MARSPEC_10m\ascii_equalarea\sss07_10m.tiff"
gdalwarp -of GTiff -multi -t_srs "+proj=cea +lon_0=0 +lat_ts=30 +x_0=0 +y_0=0 +datum=WGS84 +ellps=WGS84 +units=m +no_defs" "D:\a\data\marspec\MARSPEC_10m\ascii\sss08_10m.asc" "D:\a\data\marspec\MARSPEC_10m\ascii_equalarea\sss08_10m.tiff"
gdal_translate -of AAIGrid "D:\a\data\marspec\MARSPEC_10m\ascii_equalarea\sss08_10m.tiff" "D:\a\data\marspec\MARSPEC_10m\ascii_equalarea\sss08_10m.asc"
del "D:\a\data\marspec\MARSPEC_10m\ascii_equalarea\sss08_10m.tiff"
gdalwarp -of GTiff -multi -t_srs "+proj=cea +lon_0=0 +lat_ts=30 +x_0=0 +y_0=0 +datum=WGS84 +ellps=WGS84 +units=m +no_defs" "D:\a\data\marspec\MARSPEC_10m\ascii\sss09_10m.asc" "D:\a\data\marspec\MARSPEC_10m\ascii_equalarea\sss09_10m.tiff"
gdal_translate -of AAIGrid "D:\a\data\marspec\MARSPEC_10m\ascii_equalarea\sss09_10m.tiff" "D:\a\data\marspec\MARSPEC_10m\ascii_equalarea\sss09_10m.asc"
del "D:\a\data\marspec\MARSPEC_10m\ascii_equalarea\sss09_10m.tiff"
gdalwarp -of GTiff -multi -t_srs "+proj=cea +lon_0=0 +lat_ts=30 +x_0=0 +y_0=0 +datum=WGS84 +ellps=WGS84 +units=m +no_defs" "D:\a\data\marspec\MARSPEC_10m\ascii\sss10_10m.asc" "D:\a\data\marspec\MARSPEC_10m\ascii_equalarea\sss10_10m.tiff"
gdal_translate -of AAIGrid "D:\a\data\marspec\MARSPEC_10m\ascii_equalarea\sss10_10m.tiff" "D:\a\data\marspec\MARSPEC_10m\ascii_equalarea\sss10_10m.asc"
del "D:\a\data\marspec\MARSPEC_10m\ascii_equalarea\sss10_10m.tiff"
gdalwarp -of GTiff -multi -t_srs "+proj=cea +lon_0=0 +lat_ts=30 +x_0=0 +y_0=0 +datum=WGS84 +ellps=WGS84 +units=m +no_defs" "D:\a\data\marspec\MARSPEC_10m\ascii\sss11_10m.asc" "D:\a\data\marspec\MARSPEC_10m\ascii_equalarea\sss11_10m.tiff"
gdal_translate -of AAIGrid "D:\a\data\marspec\MARSPEC_10m\ascii_equalarea\sss11_10m.tiff" "D:\a\data\marspec\MARSPEC_10m\ascii_equalarea\sss11_10m.asc"
del "D:\a\data\marspec\MARSPEC_10m\ascii_equalarea\sss11_10m.tiff"
gdalwarp -of GTiff -multi -t_srs "+proj=cea +lon_0=0 +lat_ts=30 +x_0=0 +y_0=0 +datum=WGS84 +ellps=WGS84 +units=m +no_defs" "D:\a\data\marspec\MARSPEC_10m\ascii\sss12_10m.asc" "D:\a\data\marspec\MARSPEC_10m\ascii_equalarea\sss12_10m.tiff"
gdal_translate -of AAIGrid "D:\a\data\marspec\MARSPEC_10m\ascii_equalarea\sss12_10m.tiff" "D:\a\data\marspec\MARSPEC_10m\ascii_equalarea\sss12_10m.asc"
del "D:\a\data\marspec\MARSPEC_10m\ascii_equalarea\sss12_10m.tiff"
gdalwarp -of GTiff -multi -t_srs "+proj=cea +lon_0=0 +lat_ts=30 +x_0=0 +y_0=0 +datum=WGS84 +ellps=WGS84 +units=m +no_defs" "D:\a\data\marspec\MARSPEC_10m\ascii\sst01_10m.asc" "D:\a\data\marspec\MARSPEC_10m\ascii_equalarea\sst01_10m.tiff"
gdal_translate -of AAIGrid "D:\a\data\marspec\MARSPEC_10m\ascii_equalarea\sst01_10m.tiff" "D:\a\data\marspec\MARSPEC_10m\ascii_equalarea\sst01_10m.asc"
del "D:\a\data\marspec\MARSPEC_10m\ascii_equalarea\sst01_10m.tiff"
gdalwarp -of GTiff -multi -t_srs "+proj=cea +lon_0=0 +lat_ts=30 +x_0=0 +y_0=0 +datum=WGS84 +ellps=WGS84 +units=m +no_defs" "D:\a\data\marspec\MARSPEC_10m\ascii\sst02_10m.asc" "D:\a\data\marspec\MARSPEC_10m\ascii_equalarea\sst02_10m.tiff"
gdal_translate -of AAIGrid "D:\a\data\marspec\MARSPEC_10m\ascii_equalarea\sst02_10m.tiff" "D:\a\data\marspec\MARSPEC_10m\ascii_equalarea\sst02_10m.asc"
del "D:\a\data\marspec\MARSPEC_10m\ascii_equalarea\sst02_10m.tiff"
gdalwarp -of GTiff -multi -t_srs "+proj=cea +lon_0=0 +lat_ts=30 +x_0=0 +y_0=0 +datum=WGS84 +ellps=WGS84 +units=m +no_defs" "D:\a\data\marspec\MARSPEC_10m\ascii\sst03_10m.asc" "D:\a\data\marspec\MARSPEC_10m\ascii_equalarea\sst03_10m.tiff"
gdal_translate -of AAIGrid "D:\a\data\marspec\MARSPEC_10m\ascii_equalarea\sst03_10m.tiff" "D:\a\data\marspec\MARSPEC_10m\ascii_equalarea\sst03_10m.asc"
del "D:\a\data\marspec\MARSPEC_10m\ascii_equalarea\sst03_10m.tiff"
gdalwarp -of GTiff -multi -t_srs "+proj=cea +lon_0=0 +lat_ts=30 +x_0=0 +y_0=0 +datum=WGS84 +ellps=WGS84 +units=m +no_defs" "D:\a\data\marspec\MARSPEC_10m\ascii\sst04_10m.asc" "D:\a\data\marspec\MARSPEC_10m\ascii_equalarea\sst04_10m.tiff"
gdal_translate -of AAIGrid "D:\a\data\marspec\MARSPEC_10m\ascii_equalarea\sst04_10m.tiff" "D:\a\data\marspec\MARSPEC_10m\ascii_equalarea\sst04_10m.asc"
del "D:\a\data\marspec\MARSPEC_10m\ascii_equalarea\sst04_10m.tiff"
gdalwarp -of GTiff -multi -t_srs "+proj=cea +lon_0=0 +lat_ts=30 +x_0=0 +y_0=0 +datum=WGS84 +ellps=WGS84 +units=m +no_defs" "D:\a\data\marspec\MARSPEC_10m\ascii\sst05_10m.asc" "D:\a\data\marspec\MARSPEC_10m\ascii_equalarea\sst05_10m.tiff"
gdal_translate -of AAIGrid "D:\a\data\marspec\MARSPEC_10m\ascii_equalarea\sst05_10m.tiff" "D:\a\data\marspec\MARSPEC_10m\ascii_equalarea\sst05_10m.asc"
del "D:\a\data\marspec\MARSPEC_10m\ascii_equalarea\sst05_10m.tiff"
gdalwarp -of GTiff -multi -t_srs "+proj=cea +lon_0=0 +lat_ts=30 +x_0=0 +y_0=0 +datum=WGS84 +ellps=WGS84 +units=m +no_defs" "D:\a\data\marspec\MARSPEC_10m\ascii\sst06_10m.asc" "D:\a\data\marspec\MARSPEC_10m\ascii_equalarea\sst06_10m.tiff"
gdal_translate -of AAIGrid "D:\a\data\marspec\MARSPEC_10m\ascii_equalarea\sst06_10m.tiff" "D:\a\data\marspec\MARSPEC_10m\ascii_equalarea\sst06_10m.asc"
del "D:\a\data\marspec\MARSPEC_10m\ascii_equalarea\sst06_10m.tiff"
gdalwarp -of GTiff -multi -t_srs "+proj=cea +lon_0=0 +lat_ts=30 +x_0=0 +y_0=0 +datum=WGS84 +ellps=WGS84 +units=m +no_defs" "D:\a\data\marspec\MARSPEC_10m\ascii\sst07_10m.asc" "D:\a\data\marspec\MARSPEC_10m\ascii_equalarea\sst07_10m.tiff"
gdal_translate -of AAIGrid "D:\a\data\marspec\MARSPEC_10m\ascii_equalarea\sst07_10m.tiff" "D:\a\data\marspec\MARSPEC_10m\ascii_equalarea\sst07_10m.asc"
del "D:\a\data\marspec\MARSPEC_10m\ascii_equalarea\sst07_10m.tiff"
gdalwarp -of GTiff -multi -t_srs "+proj=cea +lon_0=0 +lat_ts=30 +x_0=0 +y_0=0 +datum=WGS84 +ellps=WGS84 +units=m +no_defs" "D:\a\data\marspec\MARSPEC_10m\ascii\sst08_10m.asc" "D:\a\data\marspec\MARSPEC_10m\ascii_equalarea\sst08_10m.tiff"
gdal_translate -of AAIGrid "D:\a\data\marspec\MARSPEC_10m\ascii_equalarea\sst08_10m.tiff" "D:\a\data\marspec\MARSPEC_10m\ascii_equalarea\sst08_10m.asc"
del "D:\a\data\marspec\MARSPEC_10m\ascii_equalarea\sst08_10m.tiff"
gdalwarp -of GTiff -multi -t_srs "+proj=cea +lon_0=0 +lat_ts=30 +x_0=0 +y_0=0 +datum=WGS84 +ellps=WGS84 +units=m +no_defs" "D:\a\data\marspec\MARSPEC_10m\ascii\sst09_10m.asc" "D:\a\data\marspec\MARSPEC_10m\ascii_equalarea\sst09_10m.tiff"
gdal_translate -of AAIGrid "D:\a\data\marspec\MARSPEC_10m\ascii_equalarea\sst09_10m.tiff" "D:\a\data\marspec\MARSPEC_10m\ascii_equalarea\sst09_10m.asc"
del "D:\a\data\marspec\MARSPEC_10m\ascii_equalarea\sst09_10m.tiff"
