mafft assembly_cluster_0.fasta bla bla bla
mafft assembly_cluster_1.fasta bla bla bla
mafft assembly_cluster_10.fasta bla bla bla
mafft assembly_cluster_100.fasta bla bla bla
mafft assembly_cluster_101.fasta bla bla bla
mafft assembly_cluster_102.fasta bla bla bla
mafft assembly_cluster_103.fasta bla bla bla
mafft assembly_cluster_104.fasta bla bla bla
mafft assembly_cluster_105.fasta bla bla bla
mafft assembly_cluster_106.fasta bla bla bla
mafft assembly_cluster_107.fasta bla bla bla
mafft assembly_cluster_108.fasta bla bla bla
mafft assembly_cluster_109.fasta bla bla bla
mafft assembly_cluster_11.fasta bla bla bla
mafft assembly_cluster_110.fasta bla bla bla
mafft assembly_cluster_111.fasta bla bla bla
mafft assembly_cluster_112.fasta bla bla bla
mafft assembly_cluster_113.fasta bla bla bla
mafft assembly_cluster_114.fasta bla bla bla
mafft assembly_cluster_115.fasta bla bla bla
mafft assembly_cluster_116.fasta bla bla bla
mafft assembly_cluster_117.fasta bla bla bla
mafft assembly_cluster_118.fasta bla bla bla
mafft assembly_cluster_119.fasta bla bla bla
mafft assembly_cluster_12.fasta bla bla bla
mafft assembly_cluster_120.fasta bla bla bla
mafft assembly_cluster_121.fasta bla bla bla
mafft assembly_cluster_122.fasta bla bla bla
mafft assembly_cluster_123.fasta bla bla bla
mafft assembly_cluster_124.fasta bla bla bla
mafft assembly_cluster_125.fasta bla bla bla
mafft assembly_cluster_126.fasta bla bla bla
mafft assembly_cluster_127.fasta bla bla bla
mafft assembly_cluster_128.fasta bla bla bla
mafft assembly_cluster_129.fasta bla bla bla
mafft assembly_cluster_13.fasta bla bla bla
mafft assembly_cluster_130.fasta bla bla bla
mafft assembly_cluster_131.fasta bla bla bla
mafft assembly_cluster_132.fasta bla bla bla
mafft assembly_cluster_133.fasta bla bla bla
mafft assembly_cluster_134.fasta bla bla bla
mafft assembly_cluster_135.fasta bla bla bla
mafft assembly_cluster_136.fasta bla bla bla
mafft assembly_cluster_137.fasta bla bla bla
mafft assembly_cluster_138.fasta bla bla bla
mafft assembly_cluster_139.fasta bla bla bla
mafft assembly_cluster_14.fasta bla bla bla
mafft assembly_cluster_140.fasta bla bla bla
mafft assembly_cluster_141.fasta bla bla bla
mafft assembly_cluster_142.fasta bla bla bla
mafft assembly_cluster_143.fasta bla bla bla
mafft assembly_cluster_144.fasta bla bla bla
mafft assembly_cluster_145.fasta bla bla bla
mafft assembly_cluster_146.fasta bla bla bla
mafft assembly_cluster_147.fasta bla bla bla
mafft assembly_cluster_148.fasta bla bla bla
mafft assembly_cluster_149.fasta bla bla bla
mafft assembly_cluster_15.fasta bla bla bla
mafft assembly_cluster_150.fasta bla bla bla
mafft assembly_cluster_151.fasta bla bla bla
mafft assembly_cluster_152.fasta bla bla bla
mafft assembly_cluster_153.fasta bla bla bla
mafft assembly_cluster_154.fasta bla bla bla
mafft assembly_cluster_155.fasta bla bla bla
mafft assembly_cluster_156.fasta bla bla bla
mafft assembly_cluster_157.fasta bla bla bla
mafft assembly_cluster_158.fasta bla bla bla
mafft assembly_cluster_159.fasta bla bla bla
mafft assembly_cluster_16.fasta bla bla bla
mafft assembly_cluster_160.fasta bla bla bla
mafft assembly_cluster_161.fasta bla bla bla
mafft assembly_cluster_17.fasta bla bla bla
mafft assembly_cluster_18.fasta bla bla bla
mafft assembly_cluster_19.fasta bla bla bla
mafft assembly_cluster_2.fasta bla bla bla
mafft assembly_cluster_20.fasta bla bla bla
mafft assembly_cluster_21.fasta bla bla bla
mafft assembly_cluster_22.fasta bla bla bla
mafft assembly_cluster_23.fasta bla bla bla
mafft assembly_cluster_24.fasta bla bla bla
mafft assembly_cluster_25.fasta bla bla bla
mafft assembly_cluster_26.fasta bla bla bla
mafft assembly_cluster_27.fasta bla bla bla
mafft assembly_cluster_28.fasta bla bla bla
mafft assembly_cluster_29.fasta bla bla bla
mafft assembly_cluster_3.fasta bla bla bla
mafft assembly_cluster_30.fasta bla bla bla
mafft assembly_cluster_31.fasta bla bla bla
mafft assembly_cluster_32.fasta bla bla bla
mafft assembly_cluster_33.fasta bla bla bla
mafft assembly_cluster_34.fasta bla bla bla
mafft assembly_cluster_35.fasta bla bla bla
mafft assembly_cluster_36.fasta bla bla bla
mafft assembly_cluster_37.fasta bla bla bla
mafft assembly_cluster_38.fasta bla bla bla
mafft assembly_cluster_39.fasta bla bla bla
mafft assembly_cluster_4.fasta bla bla bla
mafft assembly_cluster_40.fasta bla bla bla
mafft assembly_cluster_41.fasta bla bla bla
mafft assembly_cluster_42.fasta bla bla bla
mafft assembly_cluster_43.fasta bla bla bla
mafft assembly_cluster_44.fasta bla bla bla
mafft assembly_cluster_45.fasta bla bla bla
mafft assembly_cluster_46.fasta bla bla bla
mafft assembly_cluster_47.fasta bla bla bla
mafft assembly_cluster_48.fasta bla bla bla
mafft assembly_cluster_49.fasta bla bla bla
mafft assembly_cluster_5.fasta bla bla bla
mafft assembly_cluster_50.fasta bla bla bla
mafft assembly_cluster_51.fasta bla bla bla
mafft assembly_cluster_52.fasta bla bla bla
mafft assembly_cluster_53.fasta bla bla bla
mafft assembly_cluster_54.fasta bla bla bla
mafft assembly_cluster_55.fasta bla bla bla
mafft assembly_cluster_56.fasta bla bla bla
mafft assembly_cluster_57.fasta bla bla bla
mafft assembly_cluster_58.fasta bla bla bla
mafft assembly_cluster_59.fasta bla bla bla
mafft assembly_cluster_6.fasta bla bla bla
mafft assembly_cluster_60.fasta bla bla bla
mafft assembly_cluster_61.fasta bla bla bla
mafft assembly_cluster_62.fasta bla bla bla
mafft assembly_cluster_63.fasta bla bla bla
mafft assembly_cluster_64.fasta bla bla bla
mafft assembly_cluster_65.fasta bla bla bla
mafft assembly_cluster_66.fasta bla bla bla
mafft assembly_cluster_67.fasta bla bla bla
mafft assembly_cluster_68.fasta bla bla bla
mafft assembly_cluster_69.fasta bla bla bla
mafft assembly_cluster_7.fasta bla bla bla
mafft assembly_cluster_70.fasta bla bla bla
mafft assembly_cluster_71.fasta bla bla bla
mafft assembly_cluster_72.fasta bla bla bla
mafft assembly_cluster_73.fasta bla bla bla
mafft assembly_cluster_74.fasta bla bla bla
mafft assembly_cluster_75.fasta bla bla bla
mafft assembly_cluster_76.fasta bla bla bla
mafft assembly_cluster_77.fasta bla bla bla
mafft assembly_cluster_78.fasta bla bla bla
mafft assembly_cluster_79.fasta bla bla bla
mafft assembly_cluster_8.fasta bla bla bla
mafft assembly_cluster_80.fasta bla bla bla
mafft assembly_cluster_81.fasta bla bla bla
mafft assembly_cluster_82.fasta bla bla bla
mafft assembly_cluster_83.fasta bla bla bla
mafft assembly_cluster_84.fasta bla bla bla
mafft assembly_cluster_85.fasta bla bla bla
mafft assembly_cluster_86.fasta bla bla bla
mafft assembly_cluster_87.fasta bla bla bla
mafft assembly_cluster_88.fasta bla bla bla
mafft assembly_cluster_89.fasta bla bla bla
mafft assembly_cluster_9.fasta bla bla bla
mafft assembly_cluster_90.fasta bla bla bla
mafft assembly_cluster_91.fasta bla bla bla
mafft assembly_cluster_92.fasta bla bla bla
mafft assembly_cluster_93.fasta bla bla bla
mafft assembly_cluster_94.fasta bla bla bla
mafft assembly_cluster_95.fasta bla bla bla
mafft assembly_cluster_96.fasta bla bla bla
mafft assembly_cluster_97.fasta bla bla bla
mafft assembly_cluster_98.fasta bla bla bla
mafft assembly_cluster_99.fasta bla bla bla
